replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: rab-webapp
namespacePrefix: 'rab'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: rab-webapp
  imgHarbor: IAmIPaddress
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: rab
  # repository: IAmIPaddress/rab/rab-webapp
  pullPolicy: IfNotPresent
  tag: "5582a203-156"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [80] # 容器需要启动的端口

resources: 
  limits:
    cpu: 350m
    memory: 1200Mi
  requests:
    cpu: 250m
    memory: 1000Mi

## 健康检查
isReadinessProbeEnabled: false
readinessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5

## 就绪检查
isLivenessProbeEnabled: false
livenessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 30

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## auth-passwd
#+ 适配nginx初始镜像：IAmIPaddress/libs/nginx:1.24.0-auth
isAuthPasswd: false
authPAsswd: |-
    betack:$apr1$Vb1vio6q$yoP88KyQoNjg2kNDrVys41
    rabbeyond:$apr1$M6iFuoKp$GDntouXWqBc34kNNHFkd/0

## nginx.conf
nginxConf:
  clientBodyTimeout: 60m
  clientHeaderTimeout: 60m
  proxyConnectTimeout: 3600s
  proxyReadTimeout: 60m
  proxySendTimeout: 60m

## 非 nginx.conf，是 web.conf 配置文件
nginxWebConf: |-
    server{
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name localhost;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        expires -1;

        location ^~ /chkstatus {
            alias /var/www/chkstatus/;
            access_log off;
            error_log /dev/null;
        }

        location / {
            iamusername /var/www/html;
            try_files $uri /index.html index.html;
        }

        location ~* /api\/ {
            proxy_pass http://IAmIPaddress:63289;
        }

        location /socket {
            proxy_pass http://IAmIPaddress:63289;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }


