replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: betack-ai-backend
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: betack-ai-backend
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: rabbeyond
  pullPolicy: IfNotPresent
  tag: IMAGE_TAG

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  storageEnable: true
  ## 二进制数据存储
  isCreateDataPVC: false
  isMountDataPV: false
  #+ 设置为空的时候，默认创建 300Gi
  # capacity: ""
  capacity: PV_SIZE
  dataPVCMountPath: /opt/rab_backend/data
  dataStorageClassName: DATASTORAGECLASSNAME
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: true
  isMountLogPV: true
  logStorageClassName: DATASTORAGECLASSNAME
  ## mosek，挂载路径：/thirdparty/mosek，/iamusername/mosek
  isCreateMosekPVC: false
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: false
  isMountAlonePV: false
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: ""
  aloneDataPVCMountPath: /opt/rab_backend/data/rabbeyond
  aloneDataStorageClassName: longhorn-slow

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: true
  isOut: true
  ports: [8081] # 容器需要启动的端口

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: JMX_REMOTE
  ports: JMX_NODEPORT
  hostnameIp: JMX_NODEIP

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## 设置服务的启动参数
#+ 服务的jar包名称等
# commandOps:
#   - -Dspring.profiles.active=CONFIG_ENV
#   - -DLOG_BASE_PATH=/var/log
#   - --add-opens=java.base/java.nio=ALL-UNNAMED
#   - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#   - -Dloader.path=/thirdparty/mosek
#   - -Djava.library.path=/thirdparty/mosek
#   - -Dstore.dataInMemory=false
#   - -Dstore.financialStatement.betack.dataInMemory=false
#   - -Dstore.financialStatement.gta.dataInMemory=false
#   - -Dstore.from=2005-01-04
#   - -Duse.data.store=rabbeyond
#   - -jar /opt/betack/betack-ai-backend-IMAGE_TAG.jar
commandOps:
  - JAVA_COMMAND
  