replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: alpine-tools-sshd
namespacePrefix: 'rab'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: alpine
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: libs
  # repository: IAmIPaddress:8765/libs/alpine
  pullPolicy: IfNotPresent
  tag: "python3.11.3-tools"

imagePullSecrets:
  - name: harbor-inner

storage:
  isMountLogPV: true
  logPVCMountPath: /opt/betack/logs

## 设置alpine-tools-sshd ssh 登录用户 iamusername 的密码
sshPasswd: bfisnotgf

securityContext: {}

## 设置service创建类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isOut: true
  ports: [22] # 容器需要启动的端口

resources: 
  limits:
    cpu: 550m
    memory: 1200Mi
  requests:
    cpu: 350m
    memory: 800Mi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
