replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: data-subscriber-client
namespacePrefix: 'NAMESPACEPREFIX-'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: data-subscriber-client
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: bf-bsc
  # repository: IAmIPaddress:8765/bf-bsc/data-subscriber-client
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  isCreatePVC: false
  isMountDataPV: true
  ## 设置为空的时候，默认创建 300Gi
  capacity: ""
  # capacity: 500Gi
  dataPVCMountPath: /opt/saas/data
  dataStorageClassName: nfs-client-retain
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 默认会挂载日志路径：/var/log
  #+ 以及mosek的路径：/thirdparty/mosek，/iamusername/mosek
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: false
  isMountAlonePV: false
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: ""
  aloneDataPVCMountPath: ""
  aloneDataStorageClassName: nfs-client-retain

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，false 表示不创建
service:
  isIn: false
  isOut: true
  ports: [5005, 9091, 8081, 10001] # 容器需要启动的端口

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## 设置服务的启动参数
#+ 服务的jar包名称等
commandOps:
  - -Dspring.profiles.active=CONFIG_ENV
  - -Dlog.path=/var/log
  - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - --add-opens=java.base/java.io=ALL-UNNAMED
  - --add-opens=java.base/java.nio=ALL-UNNAMED
  - --add-opens=java.base/java.util=ALL-UNNAMED
  - --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
  - --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  - --add-exports=java.base/sun.util.calendar=ALL-UNNAMED
  - --add-exports=java.base/sun.security.action=ALL-UNNAMED
  # - -jar /opt/betack/data-subscriber-client.jar
