replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: saas-data-server
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: data-etl-server
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: bf-bsc
  # repository: IAmIPaddress:8765/bf-bsc/data-etl-server
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  storageEnable: true
  ## pod 缓存持久卷
  isCreateCachePVC: true
  isMountCachePV: true
  cacheCapacity: '100Gi'
  cacheStorageClassName: nfs-client-retain
  cachePodPath: /opt/saas-data/cache
  ## parquet 共享卷
  isCreateParquetPVC: true
  isMountParquetPV: true
  parquetCapacity: '500Gi'
  parquetPodMountPath: /opt/saas-data/data
  parquetStorageClassName: nfs-client-retain
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: true
  isMountLogPV: true
  logStorageClassName: nfs-client-retain
  ## mosek，挂载路径：/thirdparty/mosek，/iamusername/mosek
  isCreateMosekPVC: false
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: false
  isMountAlonePV: false
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: ""
  aloneDataPVCMountPath: ""
  aloneDataStorageClassName: nfs-client-retain

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，false 表示不创建
service:
  isIn: false
  isOut: true
  ports: [5005, 8080, 8558, 8563, 9090, 50053] # 容器需要启动的端口
headlessServices:
  ports: [10366]

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: JMX_REMOTE
  ports: JMX_NODEPORT
  hostnameIp: JMX_NODEIP

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

## 通过secret注入环境变量
envFrom:
  enabled: true
  environmentVariable:
    AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME: "saas-data-server"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

readinessProbeEnabled: false
readinessProbe:
  httpGet:
    path: /ready
    port: 8558
  periodSeconds: 30
  failureThreshold: 10
  initialDelaySeconds: 60

livenessProbeEnabled: false
livenessProbe:
  httpGet:
    path: /alive
    port: 8558
  periodSeconds: 30
  failureThreshold: 5
  initialDelaySeconds: 60

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 与 isCommandOps 二选一，将替换镜像中的command
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: false
command: ''

## 设置服务的启动参数
isCommandOps: true
commandOps:
  # - -Dspring.profiles.active=CONFIG_ENV
  # - -Dlog.path=/var/log
  # - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  # - --add-opens=java.base/java.nio=ALL-UNNAMED
  # - --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  # - --add-opens=java.base/java.io=ALL-UNNAMED
  # - --add-opens=java.base/java.lang=ALL-UNNAMED
  # - --add-exports=java.base/sun.util.calendar=ALL-UNNAMED
  # - --add-exports=java.base/sun.security.action=ALL-UNNAMED
  # - -jar /opt/betack/data-etl-server.jar
  - JAVA_COMMAND
