replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: data-insight-server
namespacePrefix: 'NAMESPACEPREFIX-'

image:
  repository: IAmIPaddress:8765/rabbeyond/data-insight-server
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [50056] # 容器需要启动的端口

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## 启动
# --port data-insight-server监听的端口
# --grpc-port 部署rabbeyond的grpc端口
# --grpc-host 部署rabbeyond的grpc主机
# --grpc-username 部署rabbeyond的用户名
# --grpc-password 部署rabbeyond的grpc密码
commands: "./data-insight-server --port 50056 --grpc-port SDK_GRPC_NODEPORT --grpc-host IAmIPaddress --grpc-username IamUserName --grpc-password secret"
