replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: rab-svc-api-app
namespacePrefix: 'rab'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: rab-svc-api-app
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: rab
  # repository: IAmIPaddress:8765/rab/rab-svc-api-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  storageEnable: false
  ## 二进制数据存储
  #+ 若 isMountDataPVType 的值为 pvc 同时又需要创建 dataPV 卷时，isCreateDataPVC 应设置为 true；
  #+ 否则其它情况一律设置为 false
  isCreateDataPVC: false
  # 指定挂载的卷类型
  #+ 若 isMountDataPVType 的值为 empty；此时 isCreateDataPVC 应设置为 false
  #+ isMountDataPVType 的值可选: empty pvc nil
  #++ pvc   表示使要 pvc 创建 pv 卷
  #++ empty 表示使用 emptyDir
  #++ nil   表示不挂载该卷
  isMountDataPVType: 'nil'
  #+ 设置为空的时候，默认创建 500Gi
  # capacity: ""
  capacity: 50Gi
  # PVC名称加中缀，默认可设置为'data'即可
  dataPVCNameInfix: 'data'
  dataPVCMountPath: /opt/rab_backend/data
  dataStorageClassName: nfs-client-retain
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: false
  isMountLogPV: false
  logStorageClassName: nfs-client-retain
  ## mosek，挂载路径：/thirdparty/mosek，/iamusername/mosek
  isCreateMosekPVC: false
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: false
  isMountAlonePV: false
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: ""
  # alonePVC名称加中缀，默认可设置为'data-alone'即可
  aloneDataPVCNameInfix: 'data-alone'
  aloneDataPVCMountPath: /opt/rab_backend/data/rabbeyond
  aloneDataStorageClassName: nfs-client-retain

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [5005, 9099, 12233] # 容器需要启动的端口

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: false
  ports: 31099
  hostnameIp: 'IAmIPaddress'

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

## 通过secret注入环境变量
#+ 启用akka集群的时候，会自动加入它相应的环境变量
envFrom:
  enabled: false
  environmentVariable: {}
    # PA_EXTERNAL_BASE_URL: "http://pa-data-sync-in-dev-1"
    # MYSQL_HOST: "IAmIPaddress"
    # MYSQL_PORT: "36806"
    # MYSQL_DATABASE: "pa"
    # MYSQL_USERNAME: "iamusername"
    # MYSQL_PASSWORD: "iampassword"

dnsNameservers:
  - IAmIPaddress
  - IAmIPaddress

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

## 此就绪探针与存活探针不能与akka集群的探针同时启用
#+ isReadinessProbeEnabled为true时表示启用此处的探针，此时akka的探针将会失效
isReadinessProbeEnabled: false
readinessProbe: {}
  #tcpSocket:
  #  port: 8080
  #initialDelaySeconds: 5
  #periodSeconds: 10
#+ 存活探针，isLivenessProbeEnabled为true时表示启用此处的探针，此时akka的探针将会失效
isLivenessProbeEnabled: false
livenessProbe: {}
  #tcpSocket:
  #  port: 8080
  #initialDelaySeconds: 15
  #periodSeconds: 20

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 与 isCommandOps 二选一，将替换镜像中的command
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: false
command: ''

## 设置服务的启动参数
isCommandOps: true
commandOps:
  - -Dspring.profiles.active=dev1
  - -DLOG_BASE_PATH=/var/log
  - --add-opens=java.base/java.nio=ALL-UNNAMED
  - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - -Dloader.path=/thirdparty/mosek/
  - -Djava.library.path=/thirdparty/mosek/
