replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: saas-data-server
namespacePrefix: 'NAMESPACEPREFIX-'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: data-etl-server
  imgHarbor: IAmIPaddress
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: bf-bsc
  # repository: IAmIPaddress/bf-bsc/data-etl-server
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  isCreatePVC: true
  isMountDataPV: true
  ## 设置为空的时候，默认创建 300Gi
  # capacity: ""
  capacity: DATA_PVC_SIZE
  dataPVCMountPath: /opt/saas/data
  dataStorageClassName: longhorn-slow
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 默认会挂载日志路径：/var/log
  #+ 以及mosek的路径：/thirdparty/mosek，/iamusername/mosek
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: false
  isMountAlonePV: false
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: ""
  aloneDataPVCMountPath: ""
  aloneDataStorageClassName: longhorn-slow

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，false 表示不创建
service:
  isIn: false
  isOut: true
  ports: [5005, 8080, 9090, 50053] # 容器需要启动的端口

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: JMX_REMOTE
  ports: JMX_NODEPORT
  hostnameIp: 'IAmIPaddress'

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## 设置服务的启动参数
#+ 服务的jar包名称等
commandOps:
  - -Dspring.profiles.active=CONFIG_ENV
  - -Xmx24G
  - -XX:MaxDirectMemorySize=16G
  - -Dlog.path=/var/log
  - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - --add-opens=java.base/java.nio=ALL-UNNAMED
  - --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  - --add-opens=java.base/java.io=ALL-UNNAMED
  - --add-opens=java.base/java.lang=ALL-UNNAMED
  - --add-exports=java.base/sun.util.calendar=ALL-UNNAMED
  - --add-exports=java.base/sun.security.action=ALL-UNNAMED
  - --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
  # - -jar /opt/betack/data-etl-server.jar
