apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfgmap
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/component: testmyql
data:
  mysql.cnf: |-
    {{- .Values.configuration | nindent 4}}

