replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: beta-chat
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: beta-chat
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: rabbeyond
  # repository: IAmIPaddress:8765/rabbeyond/beta-chat
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

storage:
  storageEnable: true
  ## 二进制数据存储
  isCreateDataPVC: true
  isMountDataPV: true
  #+ 设置为空的时候，默认创建 300Gi
  # capacity: ""
  capacity: "20Gi"
  dataPVCMountPath: /opt/betachat/models
  dataStorageClassName: longhorn-slow-replica1
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: false
  isMountLogPV: false
  logStorageClassName: longhorn-slow-replica1

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [5005] # 容器需要启动的端口

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: true
command: 'ls -lha; ADD_MODEL_TRAIN_COMMAND  TICKET_LOCK_LIFETIME=700 poetry run rasa run --enable-api --cors "*" --debug'

## 注入为环境变量
isConfigMapENV: true
configMapENVYaml: 
  TRAINING_DATA_COLLECTION_NAME: "demo_training_examples"
  RAG_HOST: "http://IAmIPaddress:32383/search"
  QDRANT_HOST: "http://IAmIPaddress:32631"
  QDRANT_KEY: "password"
  BERT_MODEL_WEIGHT: "/opt/betachat/models/bge-large-zh-v1.5"
  OPENAI_KEY: "1111111111111111111111111111111"
  TRACKER_SQL_STORE_URL: "mysql80-svc"
  TRACKER_SQL_STORE_PORT: "3306"
  TRACKER_SQL_STORE_DB: "rasa"
  TRACKER_SQL_STORE_USERNAME: "iamusername"
  TRACKER_SQL_STORE_PASSWORD: "iampassword"
  EVENT_BROKER_URL: "betanlp-kafka:9092"
  EVENT_BROKER_USERNAME: "user1"
  EVENT_BROKER_PASSWORD: "password"
  ACTION_ENDPOINT: "http://beta-chat-action-server-out-demo-1:5055/webhook"
  HTTPS_PROXY: "http://shadowsocks-rust"
