apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bf-python-project-deploy-common.fullname" . }}-{{ include "bf-python-project-deploy-common.namespacesPrefix" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bf-python-project-deploy-common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bf-python-project-deploy-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bf-python-project-deploy-common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.image.imgNameOrSvcName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.imgHarbor }}/{{ .Values.image.harborProject }}/{{ .Values.image.imgNameOrSvcName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.isCommand }}
          command:
            - /bin/sh
            - -c
            - {{ .Values.command }}
          {{- end }}
          ports:
            {{- range $.Values.service.ports }}
            - name: port-{{ . }}
              containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{- if .Values.isConfigMapENV }}
          envFrom:
          - configMapRef:
              name: {{ .Values.nameOverride }}-configmap-env
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.storage.storageEnable }}
          volumeMounts:
            {{- if .Values.storage.isMountLogPV }}
            - name: {{ include "bf-python-project-deploy-common.name" . }}-log
              mountPath: /var/log
            {{- end }}
            {{- if .Values.storage.isMountDataPV }}
            - name: {{ include "bf-python-project-deploy-common.name" . }}-data
              mountPath: {{ .Values.storage.dataPVCMountPath }}
            {{- end }}
          {{- end }}
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
        - IAmIPaddress
        - IAmIPaddress
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.storageEnable }}
      volumes:
        {{- if .Values.storage.isMountLogPV }}
        - name: {{ include "bf-python-project-deploy-common.name" . }}-log
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-log-pvc
        {{- end }}
        {{- if .Values.storage.isMountDataPV }}
        - name: {{ include "bf-python-project-deploy-common.name" . }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-{{ include "bf-python-project-deploy-common.dataPVCNameInfix" . }}data-pvc
        {{- end }}
      {{- end }}

