replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: beta-llm-embedding
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: beta-llm-embedding
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: rabbeyond
  # repository: IAmIPaddress:8765/rabbeyond/beta-llm-embedding
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

storage:
  storageEnable: true
  ## 二进制数据存储
  isCreateDataPVC: true
  isMountDataPV: true
  #+ 设置为空的时候，默认创建 300Gi
  capacity: "20Gi"
  # capacity: 500Gi
  # PVC名称加中缀
  dataPVCNameInfix: 'llm'
  dataPVCMountPath: /opt/betack/data
  dataStorageClassName: nfs-client-retain
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: false
  isMountLogPV: false
  logStorageClassName: nfs-client-retain

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [8099] # 容器需要启动的端口

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: true
command: 'ls -lh; ./SVCSTARTNAME --path config.yaml'

## config.yaml 配置文件
configYaml: |-
    server_port: 8099
    bert:
      dir: "/opt/betack/data/bge-large-zh-v1.5"
    qdrant_client:
      host: "http://IAmIPaddress"
      http_port: 32631
      grpc_port: 31237
      api_key: "password"

