apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-mysql-secret
type: Opaque
stringData:
  my.password: |
    [client]
    user={{ .Values.mysql.username | default "iamusername" }}
    password={{ .Values.mysql.password | default "iampassword" }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-storage-server-secret
type: Opaque
stringData:
  STORAGE_USERNAME: {{ .Values.storage.username | default "betack" }}
  STORAGE_PASSWORD: {{ .Values.storage.password | default "bfisnotgf" }}
  STORAGE_IPADDR: {{ .Values.storage.ipaddr | default "IAmIPaddress" }}
  STORAGE_DIR: {{ .Values.storage.storageDir | default "/mnt/data-1/nfs/backups" }}