replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: prod-smoke-api4
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: prod-smoke-api4
  imgHarbor: IAmIPaddress
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: qa-smoke
  pullPolicy: IfNotPresent
  tag: IMAGE_TAG

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  storageEnable: true
  ## 二进制数据存储
  isCreateDataPVC: false
  isMountDataPV: false
  #+ 设置为空的时候，默认创建 300Gi
  # capacity: ""
  capacity: PV_SIZE
  dataPVCMountPath: /opt/rab_backend/data
  dataStorageClassName: DATASTORAGECLASSNAME
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: false
  isMountLogPV: false
  logStorageClassName: DATASTORAGECLASSNAME
  ## mosek，挂载路径：/thirdparty/mosek，/iamusername/mosek
  isCreateMosekPVC: false
  isMountMosekPV: false
  mosekStorageClassName: nfs-client-retain
  ## 有些服务，除了需要挂载api的data pv卷，还需要自己独立的pv卷
  isCreateAlonePVC: true
  isMountAlonePV: true
  #+ 设置为空的时候，默认创建 300Gi
  aloneCapacity: "50Gi"
  aloneDataPVCMountPath: /iamusername/.m2
  aloneDataStorageClassName: longhorn-fast

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: true
  ports: [22] # 容器需要启动的端口

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: false

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 与 isCommandOps 二选一，将替换镜像中的command
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: false
command: ''

## 设置服务的启动参数
#+ 服务的jar包名称等
isCommandOps: false
commandOps: []
  