{{- if .Values.envFrom.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-db-and-others-secret
type: Opaque
stringData:
  {{- if .Values.envFrom.enabled }}
  {{- toYaml .Values.envFrom.environmentVariable | nindent 2 }}
  {{- end }}
{{- end }}