{{- if or .Values.envFrom.enabled .Values.akka.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-db-and-others-secret
type: Opaque
stringData:
  {{- if .Values.envFrom.enabled }}
  {{- toYaml .Values.envFrom.environmentVariable | nindent 2 }}
  {{- end }}
  {{- if .Values.akka.enabled }}
  {{- toYaml .Values.akka.akkaEnvironmentVariable | nindent 2 }}
  {{- end }}
{{- end }}