replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: global-security-data-source
namespacePrefix: 'NAMESPACEPREFIX'

image:
  # imgNameOrSvcName 是指定的镜像名称或者服务名称，
  imgNameOrSvcName: global-security-data-source
  imgHarbor: IAmIPaddress:8765
  # harborProject 是harbor镜像仓库中创建的项目名称
  harborProject: bf-bsc
  # repository: IAmIPaddress:8765/rabbeyond/global-security-data-source
  pullPolicy: IfNotPresent
  tag: "IMAGE_TAG"

storage:
  storageEnable: false
  ## 二进制数据存储
  isCreateDataPVC: false
  isMountDataPV: false
  #+ 设置为空的时候，默认创建 300Gi
  # capacity: ""
  capacity: "10Gi"
  # PVC名称加中缀，特殊情况下使用，默认可设置为空，即''
  dataPVCNameInfix: ''
  dataPVCMountPath: /opt/betack/data
  dataStorageClassName: nfs-client-retain
  ## 日志存储，挂载日志存储路径：/var/log
  isCreateLogPVC: false
  isMountLogPV: false
  logStorageClassName: nfs-client-retain

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，fasle 表示不创建
service:
  isIn: false
  isOut: false
  ports: [] # 容器需要启动的端口

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling: {}
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

### isCommand 
#+ 或者是都设置为false，即不设置 command，此时默认用镜像中的command
## 用于直接指定command的项目
isCommand: true
# command: 'ls -lha; poetry shell; poetry run poe run'
command: 'ls -lha; python -m global_secu_data_source'

## 注入为环境变量
isConfigMapENV: false
configMapENVYaml:
    MYSQL_HOST: "IAmIPaddress"
    MYSQL_PORT: "53306"
    MYSQL_USER: "iamusername"
    MYSQL_PSD: "bfisnotgf"
    MYSQL_FILE_META_DATABASE: "spiderman"
