# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: mssql-server-2019

image:
  harbor: IAmIPaddress:8765
  repository: IAmIPaddress:8765/libs/mssql-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-latest"

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

mssql:
  iamusernamePassword: beifa!888

storage:
  capacity: 80Gi
  storageClassName: nfs-client-retain

# 设置所使用的用户与组id
securityContext: {}

service:
  type: NodePort
  port: 1433

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

