apiVersion: v1
kind: Pod
metadata:
  name: alpine-tools
spec:
  containers:
    - name: alpine-tools
      image: harbor.betack.com/libs/alpine:tools
      # command: ["/bin/sh", "-c", "cat"]
      ## 经过验证，在k8s集群版本：v1.23.6+rke2r2
      #+ 用 command: ["/bin/sh", "-c", "cat"]，导致在k8s集群中，一直启动失败
      command: ["/bin/sh", "-c", 'for i in `seq 1 1000000`; do sleep 600; done;']
      resources:
        limits:
          cpu: 550m
          memory: 1200Mi
      volumeMounts:
      - name: saas-app-server-data
        mountPath: /opt/saas_commons/data
  dnsConfig:
    nameservers:
    - IAmIPaddress
    - IAmIPaddress
  imagePullSecrets:
  - name: harbor-outer
  volumes:
    - name: saas-app-server-data
      persistentVolumeClaim:
        claimName: bf-bsc-staging-1-data-pvc

