replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: saas-etl-server

image:
  repository: 'IAmIPaddress/bf-bsc/saas-etl-server'
  pullPolicy: IfNotPresent
  tag: 'IMAGE_TAG'

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

storage:
  ## 设置为空的时候，默认创建 300Gi
  capacity: ""
  # capacity: 500Gi

securityContext: {}

## 设置service创建类型
#+ isIn 为 true，表示创建 ClusterIP 类型
#+ isOut 为 true，表示创建 NodePort 类型，false 表示不创建
service:
  isIn: false
  isOut: true
  ports: [1125, 5005, 9099] # 容器需要启动的端口

## 设置是否开启jmxremote调试
#+ isopen 为 true，表示创建 NodePort 类型的service；fasle 表示不创建
#+ ports: 31099，这个31099既是jmxremote的端口，同时也是NodePort的端口
#+ hostnameIp 是k8s集群节点的ip
jmxremote:
  isopen: JMX_REMOTE
  ports: JMX_NODEPORT
  hostnameIp: 'IAmIPaddress'

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# commands: "java JAVA_JAR_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dspring.profiles.active=CONFIG_ENV -Drab.beyond.parentDirectory=/opt/saas_commons/data/rabbeyond -Duse.parquet.parentDirectory=/opt/saas_commons/data/betack/betack-code -DdbSchemaMap.aShare=saas_new -Dserver.port=1125 -Dmanagement.server.port=9099 -Xmx4096m -jar /opt/betack/saas-etl-server-IMAGE_TAG.jar"
## 设置服务的启动参数
#+ 服务的jar包名称等
commandOps:
  - -Dspring.profiles.active=CONFIG_ENV
  - -DLOG_BASE_PATH=/var/log JAVA_JAR_OPTS
  # - --add-opens=java.base/java.nio=ALL-UNNAMED
  - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - -Drab.beyond.parentDirectory=/opt/saas_commons/data/rabbeyond
  - -Duse.parquet.parentDirectory=/opt/saas_commons/data/betack/betack-code
  - -DdbSchemaMap.aShare=saas_new
  - -Dserver.port=1125
  - -Dmanagement.server.port=9099
  - -Xmx4096m
  - -jar /opt/betack/saas-etl-server-IMAGE_TAG.jar
