# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5
nameOverride: mysql

global:
  namespacePrefix: 'rab'
  image:
    repository: IAmIPaddress:8765/libs/mysql
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "8.0.35-debian"

backupMysqlDBCronjob:
  enabled: true
  nameOverride: backup-mysql80-db-cronjob
  cronjob:
    ## 因控制器时区的问题，如果是CST，则为：0 10 * * *
    #+ 但控制器时区是UTC，需要减 8
    schedule: "0 16 * * *"
  mysql:
    mysqlSVCName: 'mysql80-svc'

imagePullSecrets:
  - name: harbor-inner
  - name: harbor-outer

mysql:
  iamusernamePassword: iampassword

storage:
  capacity: 100Gi
  storageClassName: longhorn-fast

securityContext: {}

service:
  type: NodePort
  port: 3306

resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

# https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
configuration: |-
  [mysqld]
  default_authentication_plugin=caching_sha2_password
  pid-file        = /var/run/mysqld/mysqld.pid
  socket          = /var/run/mysqld/mysqld.sock
  datadir         = /var/lib/mysql
  symbolic-links=0
  max_connections=10000
  bind-address=IAmIPaddress
  default-time-zone='+8:00'
  #secure-file-priv= NULL
  #skip-name-resolve
  #secure_file_priv=/var/lib/mysql
  #sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  net_read_timeout = 60
  net_write_timeout = 60
  max_allowed_packet = 512M
  default_storage_engine = InnoDB
  innodb_file_per_table = 1
  innodb_open_files = 65535
  innodb_buffer_pool_size = 24G
  innodb_buffer_pool_chunk_size = 512M
  innodb_write_io_threads = 16
  innodb_read_io_threads = 16
  innodb_thread_concurrency = 0
  innodb_purge_threads = 10
  innodb_flush_log_at_trx_commit = 1
  innodb_log_buffer_size = 16M
  innodb_log_file_size = 2G
  innodb_log_files_in_group = 3
  innodb_max_dirty_pages_pct = 90
  innodb_lock_wait_timeout = 120
  
  [client]
  default-character-set=utf8

  [mysql]
  default-character-set=utf8
