apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  10240;
        multi_accept on;
        use epoll;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        server_names_hash_bucket_size 128;
        client_header_buffer_size 128k;
        large_client_header_buffers 4 128k;
        client_max_body_size 1440m;
        client_body_timeout   {{ .Values.nginxConf.clientBodyTimeout }};
        client_header_timeout {{ .Values.nginxConf.clientHeaderTimeout }};
        proxy_connect_timeout {{ .Values.nginxConf.proxyConnectTimeout }};
        proxy_read_timeout    {{ .Values.nginxConf.proxyReadTimeout }};
        proxy_send_timeout    {{ .Values.nginxConf.proxySendTimeout }};
        sendfile on;
        underscores_in_headers on;
        tcp_nopush     on;
        types_hash_max_size 2048;
        keepalive_timeout 600;
        tcp_nodelay on;
        fastcgi_connect_timeout 600;
        fastcgi_send_timeout 600;
        fastcgi_read_timeout 600;
        fastcgi_buffer_size 256k;
        fastcgi_buffers 8 128k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        set_real_ip_from IAmIPaddress/8;
        set_real_ip_from IAmIPaddress;
        set_real_ip_from IAmIPaddress/8;
        real_ip_header X-Forwarded-For;
        server_tokens off;
        gzip  on;
        gzip_min_length  1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.0;
        gzip_comp_level 2;
        gzip_types      application/wasm text/plain application/javascript application/xhtml+xml application/x-javascript text/css application/xml text/javascript application/json image/webp image/apng image/jpeg image/gif image/png;
        # gzip_vary on;
        gzip_vary off;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
        include /etc/nginx/conf.d/*.conf;
    }
 
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-nginx-web-conf
data:
  default.conf: |-
    {{- .Values.nginxWebConf | nindent 4}}

---

{{ if .Values.isAuthPasswd }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-nginx-authpasswd
data:
  passwd: |-
    {{- .Values.authPAsswd | nindent 4}}
{{ end }}