apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.name" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity | quote }}
  storageClassName: {{ .Values.storage.storageClassName }}
  