apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-iamusername-password: {{ .Values.mysql.iamusernamePassword | b64enc | quote }}