apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.name" . }}-statefuleset
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "mysql.name" . }}-svc
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mysql.name" . }}-{{ .Release.Namespace }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          # args: ["--default-authentication-plugin=mysql_native_password"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: MYSQL_iamusername_PASSWORD
            # value: iampassword
            valueFrom:
             secretKeyRef:
               name: {{ include "mysql.name" . }}-secret
               key: mysql-iamusername-password
          ports:
          - name: mysql
            containerPort: {{ .Values.service.port }}
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
            subPath: mysql
          - name: config
            mountPath: /etc/mysql/my.cnf
            subPath: my.cnf
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mysql.name" . }}-pvc
      - name: config
        configMap:
          name: {{ .Release.Name }}-cfgmap