apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
type: Opaque
data:
  mssql-sa-password: {{ .Values.mssql.iamusernamePassword | b64enc | quote }}



