apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.name" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "mssql.selectorLabels" . | nindent 4 }}
