apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mssql.name" . }}-statefuleset
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "mssql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "mssql.name" . }}-svc
  template:
    metadata:
      labels:
        {{- include "mssql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ## 使用初始化容器，解决目录/var/opt/mssql权限问题
      #+ 具体权限，见 README.MD 笔记
      initContainers:
      - image: {{ .Values.image.harbor }}/libs/alpine:3.15.4-ansible
        command: ["/bin/sh", "-c", "cd /var/opt && chmod 770 mssql"]
        imagePullPolicy: IfNotPresent
        name: chauth
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql
          subPath: mssql
      containers:
        - name: {{ include "mssql.name" . }}-{{ .Release.Namespace }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # args: ["--default-authentication-plugin=mssql_native_password"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: MSSQL_SA_PASSWORD
            valueFrom:
             secretKeyRef:
               name: {{ include "mssql.name" . }}-secret
               key: mssql-sa-password
          ports:
          - name: mssql
            containerPort: {{ .Values.service.port }}
          volumeMounts:
          - name: data
            mountPath: /var/opt/mssql
            subPath: mssql
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mssql.name" . }}-data-pvc
